Fix: TaskVariableEntity model is introduced, corresponding changes and tests are corrected or added.
Activiti/activiti-cloud-query-service pull request #120
Opened 2018-11-16 20:56 UTC by CTI777

Test version for the new TaskVariableEntity model. Changes for new admin entry point for task/processInstance variables.

2018-12-04 17:23 UTC, erdemedeiros requested changes
Great job @CTI777. Some minor changes to do and it's ok for me.

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/ProcessVariableEntity.java
> +@Entity(name="Variable")
Maybe it could be renamed to `ProcessVariable`

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/ProcessVariableEntity.java
> +@Table(	name = "VARIABLE",
Could be renamed to `PROCESS_VARIABLE`

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-model/src/main/java/org/activiti/cloud/services/query/model/TaskVariableEntity.java
> +@Table(	name = "TASKVARIABLE",
Rename from `TASKVARIABLE` to `TASK_VARIABLE`.

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/VariableCreatedEventHandler.java
> +           //Task variable
I think this comment is not necessary. It can be inferred from `if` condition.

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/VariableCreatedEventHandler.java
> +                createVariableEntity(variableCreatedEvent);
the method can be renamed to `createProcessVariableEntity` and the comment from previous line can be removed.

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/VariableCreatedEventHandler.java
> +    //Create Task Variable
This comment can be removed. The method name is clear enough.

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/VariableCreatedEventHandler.java
> +        //Check that valid
I think this comment can be removed.

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/VariableCreatedEventHandler.java
> +    //Create Process Variable
Comment can be removed and method renamed to CreateProcessVariableEntity

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/VariableCreatedEventHandler.java
> +        //Check that valid
Comment can be removed.

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/VariableUpdater.java
> +    public void update(ProcessVariableEntity updatedVariableEntity, Predicate predicate, String notFoundMessage) {
Maybe the class should be renamed to ProcessVariableUpdater.

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessInstanceVariableAdminController.java
> +        value = "/admin/v1/process-instances/{processInstanceId}/"+VariableRelProvider.COLLECTION_RESOURCE_REL,
Actually I don't think you should use `VariableRelProvider.COLLECTION_RESOURCE_REL` here, as it's intended to give the relation collection name in HAL responses. (see https://github.com/Activiti/Activiti/issues/1745). In the case of variables the value in the content and the value in the path will be the same (`variables`), but for other resources it will be different `processDefinitions` (RelProvider) vs `process-definitions` (request path). So you should either switch back to plain string as before or create another constant for that somewhere else.

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessInstanceVariableAdminController.java
> +    public VariableResource findById(@PathVariable long variableId) {
I don't think we want to provide this end point as it's not available in the runtime bundle. @salaboy what do you think?

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessInstanceVariableController.java
> +    public VariableResource findById(@PathVariable long variableId) {
Same here. I don't think we want this endpoint.

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/TaskAdminController.java
> +        value = "/admin/v1/" + TaskRelProvider.COLLECTION_RESOURCE_REL,
Same remark concerning the use of relProvider to construct the url path. You cannot it rel provider for that.

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/TaskVariableAdminController.java
> +        value = "/admin/v1/tasks/{taskId}/"+VariableRelProvider.COLLECTION_RESOURCE_REL,
Don't use relProvider.

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/TaskVariableAdminController.java
> +    @RequestMapping(value = "/{variableId}", method = RequestMethod.GET)
Same as for process variables, I don't think we want this endpoint.

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/TaskVariableController.java
> +        value = "/v1/tasks/{taskId}/"+VariableRelProvider.COLLECTION_RESOURCE_REL,
Don't use RelProvider.

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/TaskVariableController.java
> +    @RequestMapping(value = "/{variableId}", method = RequestMethod.GET)
I don't think we want this endpoint.

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/assembler/ProcessInstanceVariableResourceAssembler.java
> +        Link selfRel = linkTo(methodOn(ProcessInstanceVariableController.class).findById(entity.getId())).withSelfRel();
In the specific case of variables I think we don't need to provide a self link, as we are always retrieving a collection of variables (variables of process or variables of tasks).

2018-12-04 17:23 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/assembler/TaskVariableResourceAssembler.java
> +        Link selfRel = linkTo(methodOn(TaskVariableController.class).findById(entity.getId())).withSelfRel();
Same here. I think we can remove the self link.

2018-12-04 17:26 UTC, salaboy commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessInstanceVariableAdminController.java
> +    public VariableResource findById(@PathVariable long variableId) {
@CTI777 @erdemedeiros we already discussed it with @CTI777 we don;'t need the /variables/ end point.. so if @CTI777 can remove that it will be great.

2018-12-06 10:53 UTC, erdemedeiros approved these changes

2018-12-06 10:53 UTC, merged