After completion of the task candidateGroups and candidateUsers will not be removed
Activiti/activiti-cloud-query-service pull request #231
Opened 2019-04-29 17:56 UTC by CTI777

Related to https://github.com/Activiti/Activiti/issues/2669

2019-04-29 18:00 UTC, CTI777 commented
@salaboy @erdemedeiros 
Events for candidates (User and Groups) removal will not be handled when task is completed / cancelled / deleted. Should we consider here also remove of task variables?

2019-05-16 09:02 UTC, erdemedeiros requested changes

2019-05-16 09:02 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/TaskCandidateGroupRemovedEventHandler.java
> +            if (taskStatus != TaskStatus.CREATED &&
@CTI777, as this logic is going to be used a couple of times (here and for candidate groups) let's move part of the logic to the enum `TaskStatus` so that we can leverage this `if` statement.
[TaskStatus](https://github.com/Activiti/activiti-api/blob/develop/activiti-api-task-model/src/main/java/org/activiti/api/task/model/Task.java#L23) can be changed as the following:
``` java
enum TaskStatus {
        CREATED(false),
        ASSIGNED(false),
        SUSPENDED(false),
        COMPLETED(true),
        CANCELLED(true),
        DELETED(true);

        private final boolean finalState;

        TaskStatus(boolean finalState) {
            this.finalState = finalState;
        }

        public boolean isFinalState() {
            return finalState;
        }
    }
```

Then you can use `findResult.get().getStatus().isFinalStatus()`.

@CTI777, also if you don't mind I'd prefer an `if` block wrapping `delete` logic than an early `return`. I mean:
``` java
if(!findResult.get().getStatus().isFinalStatus()) {
//delete operation
}
```

2019-05-24 13:25 UTC, CTI777 commented
@salaboy @erdemedeiros 
Should work better now...

2019-05-24 14:24 UTC, salaboy approved these changes

2019-05-24 14:37 UTC, merged