Refactoring of events for variables creation, update and delete
Activiti/activiti-cloud-query-service pull request #232
Opened 2019-05-06 15:53 UTC by CTI777

Related to https://github.com/Activiti/Activiti/issues/2724

2019-05-06 18:29 UTC, CTI777 commented
@salaboy @erdemedeiros 
After checking handling of task variable deletion following interesting things are found to discuss:

- **If we delete a task variable we set a flag that it is deleted**  - do we really need to throw an exception if variable is already deleted 

- **If we create a variable there is no check that variable already exists**: have added a check here

- **If we update a variable we do not check if it is already deleted**: have added the check here

- **When we query variables, all variables are returned (deleted and existing)**: will it have a sense to return always (or by default) only existing variables (do not include deleted variables at all). Otherwise it is possible that a value of the deleted variable will be used…

2019-05-07 20:46 UTC, CTI777 commented
@salaboy @erdemedeiros @igdianov 
Handling events related to task variables (as an example) may lead sometime to exceptions (not found variable, variable already exists, etc.) Catching of such kind of exceptions is not implemented, and this leads for repetitive sending of events with following exceptions again.. Even testing becomes painful when some messages are hanging in RabbitMQ and suddenly appears in unpredictable places. 
**Can we once discuss such kind of problems**?
Thrown exceptions (which are correct from business logic) will be accumulated in production system and may slow down everything dramatically...

2019-05-16 09:40 UTC, erdemedeiros requested changes

2019-05-16 09:40 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/ProcessVariableUpdateEventHandler.java
> +                        QProcessVariableEntity.processVariableEntity.markedAsDeleted.eq(Boolean.FALSE)
As discussed previously, let's stop using `markedAsDeleted` flag and use real deletes.

2019-05-16 09:40 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/TaskVariableDeletedEventHandler.java
> +            TaskStatus taskStatus = taskEntity.get().getStatus();
Reuse `taskEntity.get().getStatus().isFinalStatus()`. See https://github.com/Activiti/activiti-cloud-query-service/pull/231#discussion_r284597687.

2019-05-16 09:40 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/TaskVariableUpdatedEventHandler.java
> +        BooleanExpression predicate = QTaskVariableEntity.taskVariableEntity.name.eq(String.valueOf(variableName))
Are you sure this extra `String.valueOf` is necessary here? `variableName` is already a String.

2019-05-16 09:40 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/TaskVariableUpdatedEventHandler.java
> +                        QTaskVariableEntity.taskVariableEntity.markedAsDeleted.eq(Boolean.FALSE)
No longer necessary.

2019-05-16 09:40 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/VariableCreatedEventHandler.java
> +                        QTaskVariableEntity.taskVariableEntity.markedAsDeleted.eq(Boolean.FALSE)
No longer necessary.

2019-05-16 09:40 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/VariableCreatedEventHandler.java
> +            throw new IllegalStateException("Variable " + variableName + " already exists in the task " + taskId + "!");
I think in this case you can log a message and ignore the event.

2019-05-16 09:40 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/VariableCreatedEventHandler.java
> +                        QProcessVariableEntity.processVariableEntity.markedAsDeleted.eq(Boolean.FALSE)
No longer necessary.

2019-05-16 09:40 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/events/handlers/VariableCreatedEventHandler.java
> +            throw new IllegalStateException("Variable " + variableName + " already exists in the process " + processInstanceId + "!");
I think you can log the exception and ignore the event in this case.

2019-05-16 09:40 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessInstanceVariableAdminController.java
> +                                       .and(variable.markedAsDeleted.eq(Boolean.FALSE));
No longer necessary.

2019-05-16 09:40 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/ProcessInstanceVariableController.java
> +                                       .and(variable.markedAsDeleted.eq(Boolean.FALSE));
No longer necessary.

2019-05-16 09:40 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/TaskVariableAdminController.java
> +                                       .and(variable.markedAsDeleted.eq(Boolean.FALSE));
No longer necessary.

2019-05-16 09:40 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/main/java/org/activiti/cloud/services/query/rest/TaskVariableController.java
> +                                       .and(variable.markedAsDeleted.eq(Boolean.FALSE));
No longer necessary.

2019-05-16 09:40 UTC, erdemedeiros commented on activiti-cloud-services-query/activiti-cloud-services-query-rest/src/test/java/org/activiti/cloud/services/query/events/handlers/TaskEntityVariableEntityDeletedEventHandlerTest.java
> +        TaskEntity taskEntity = new TaskEntity();
This test should be renamed as we are no longer using soft deletes.

2019-05-16 14:42 UTC, CTI777 commented
@erdemedeiros @salaboy 
Have made refactoring. 
For task variables status of the task is checked (and nothing is deleted if task ended)
For process variables status of the process is not checked, variables are always deleted
Is this Ok?
If not Ok, 
maybe we can do following:
If process is completed: mark process variables as Deleted (soft deletion)

2019-05-24 14:25 UTC, salaboy approved these changes

2019-05-24 15:01 UTC, merged